include:
  - local: ".gitlab-ci/.lint.yml"
  - local: ".gitlab-ci/.build.yml"
  - local: ".gitlab-ci/.deploy.yml"
  - local: ".gitlab-ci/.notify.yml"
  - local: ".gitlab-ci/.rollback.yml"

variables:
  APP_VERSION: "v0.$CI_PIPELINE_IID"

.docker-login:
  before_script:
    - echo "Login to Gitlab Registry..."
    - docker login -u $CI_REGISTRY_USER -p $MY_PROJECT_TOKEN $CI_REGISTRY

stages:
  - lint
  - build
  - deploy
  - notify
  - rollback
