include:
  - local: ".gitlab-ci/.lint.yml"
  - local: ".gitlab-ci/.build.yml"
  - local: ".gitlab-ci/.deploy.yml"
  - local: ".gitlab-ci/.notify.yml"

variables:
  APP_VERSION: "v0.0.$CI_PIPELINE_IID"

stages:
  - lint
  - build
  - deploy
  - notify
