build_job:
  stage: build
  extends: .docker-login
  needs:
    - job: lint_job
  script:
    - echo APP_VERSION="v0.$CI_PIPELINE_IID" > .env
    - echo "Building docker images..."
    - echo "Building image $CI_REGISTRY_IMAGE/server:$APP_VERSION"
    - docker build -t $CI_REGISTRY_IMAGE/server:$APP_VERSION  ./server
    - echo "Building image $CI_REGISTRY_IMAGE/nginx:$APP_VERSION"
    - docker build -t $CI_REGISTRY_IMAGE/nginx:$APP_VERSION ./nginx
    - echo "Building image $CI_REGISTRY_IMAGE/client:$APP_VERSION"
    - docker build -t $CI_REGISTRY_IMAGE/client:$APP_VERSION ./client
    - echo "All the images have been built!"
    - echo "Sending image to Gitlab Registry..."
    - docker push $CI_REGISTRY_IMAGE/server:$APP_VERSION
    - docker push $CI_REGISTRY_IMAGE/nginx:$APP_VERSION
    - docker push $CI_REGISTRY_IMAGE/client:$APP_VERSION
    - echo "All images have been sent to Gitlab Registry!"
  artifacts:
    reports:
      dotenv: .env
  only:
    - master
