build_job:
  stage: build
  script:
    - echo "Login to Gitlab Registry..."
    - docker login -u $CI_REGISTRY_USER -p $MY_PROJECT_TOKEN $CI_REGISTRY
    - echo "Building docker images..."
    - echo "Building image $CI_REGISTRY_IMAGE/server:$IMAGE_TAG"
    - docker buildx build -t $CI_REGISTRY_IMAGE/server:$IMAGE_TAG --cache-from $CI_REGISTRY_IMAGE/server:latest ./server
    - echo "Building image $CI_REGISTRY_IMAGE/nginx:$IMAGE_TAG"
    - docker buildx build -t $CI_REGISTRY_IMAGE/nginx:$IMAGE_TAG --cache-from $CI_REGISTRY_IMAGE/nginx:latest ./nginx
    - echo "Building image $CI_REGISTRY_IMAGE/client:$IMAGE_TAG"
    - docker buildx build -t $CI_REGISTRY_IMAGE/client:$IMAGE_TAG --cache-from $CI_REGISTRY_IMAGE/client:latest ./client
    - echo "All the images have been built!"
    - echo "Sending image to Gitlab Registry..."
    - docker push $CI_REGISTRY_IMAGE/server:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/nginx:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE/client:$IMAGE_TAG
    - echo "All images have been sent to Gitlab Registry!"
