deploy_job:
  stage: deploy
  needs:
    - job: build_job
  script:
    - echo "Login to Gitlab Registry..."
    - echo "Stopping all containers..."
    - docker compose down --remove-orphans
    - echo "Deleting all old images for application..."
    - >
      images=$(docker images --filter=reference="$CI_REGISTRY_IMAGE/*" --format "{{.ID}}") &&
      if [ -n "$images" ]; then
          docker rmi -f $images;
      else
          echo "There are no images to delete";
      fi
    - docker images
    - echo "Pulling latest images for application..."
    - docker compose pull
    - echo "Container startup..."
    - docker compose up -d --force-recreate
    - echo "Application successfully deployed!"
  only:
    - master
  environment: production
