deploy_job:
  stage: deploy
  extends: .docker-login
  needs:
    - job: build_job
  script:
    - sh cleaning.sh
    - docker images
    - sh deploy.sh
  only:
    - master
  environment: production
