deploy_job:
  stage: deploy
  script:
    - echo "Login to Gitlab Registry..."
    - docker login -u $CI_REGISTRY_USER -p $MY_PROJECT_TOKEN $CI_REGISTRY
    - echo "Stopping all containers..."
    - docker compose down --remove-orphans
    - echo "Deleting all old images for application..."
    - docker rmi -f $(docker images --filter=reference=$CI_REGISTRY_IMAGE/* --format "{{.ID}}")
    - echo "Pulling latest images for application..."
    - docker compose pull
    - echo "Container startup..."
    - docker compose up -d --force-recreate
    - echo "Application successfully deployed!"
  environment: production
