deploy_job:
  stage: deploy
  extends: .docker-login
  needs:
    - job: build_job
  script:
    - chmod ugo+x cleaning.sh
    - bash cleaning.sh
    - docker images
    - echo "Pulling latest images for application..."
    - docker compose pull
    - echo "Container startup..."
    - docker compose up -d --force-recreate
    - echo "Application successfully deployed!"
  only:
    - master
  environment: production
