deploy_job:
  stage: deploy
  extends: .docker-deploy
  needs:
    - job: build_job
  script:
    - echo APP_VERSION="v0.$CI_PIPELINE_IID" > .env
  artifacts:
    reports:
      dotenv: .env
  environment: production
