lint_job:
  stage: lint
  image: node:20-slim
  script:
    - cd server
    - echo "Install packages for a folder 'server'..."
    - npm install
    - echo "Checking files from a folder 'server'..."
    - npm run lint > lint-results-server.txt
    - cd ..
    - cd client
    - echo "Install packages for a folder 'client'..."
    - npm install
    - echo "Checking files from a folder 'client'..."
    - npm run lint > lint-results-client.txt
    - cd ..
    - echo "All files have been verified!"
  artifacts:
    paths:
      - lint-results-server.txt
      - lint-results-client.txt
    expire_in: 3 day
