lint_job:
  stage: lint
  image: node:20.17.0-slim
  script:
    - chmod ugo+x lint.sh
    - cd server
    - echo "Install packages for a folder 'server'..."
    - npm install
    - sh ../.gitlab-ci/lint.sh server
    - cd ..
    - cd client
    - echo "Install packages for a folder 'client'..."
    - npm install
    - sh ../.gitlab-ci/lint.sh client
    - cd ..
    - echo "All files have been verified!"
  artifacts:
    paths:
      - lint_output.txt
    when: always
    expire_in: 1 day
