lint_job:
  stage: lint
  image: node:20-slim
  script:
    - cd server
    - echo "Install packages for a folder 'server'..."
    - npm install
    - echo "Checking files from a folder 'server'..."
    - npm run lint
    - cd ..
    - cd client
    - echo "Install packages for a folder 'client'..."
    - npm install
    - echo "Checking files from a folder 'client'..."
    - npm run lint
    - cd ..
    - echo "All files have been verified!"
