.notify:
  stage: notify
  needs:
    - job: deploy_job
  before_script:
    - apk add curl
    - chmod +x notify.sh
    - echo "Notification sending..."
  only:
    - master

variables:
  MESSAGE_SUCCESS: "*Deployment for $CI_PROJECT_NAME Successfull* 👌 \\n\\n*New App Version* _ $APP_VERSION _ \\n\\n[Open Website](http://127.0.0.1:3050/)"
  MESSAGE_FAILURE: "*Deployment for $CI_PROJECT_NAME Failed* ❌ \\n\\n*Please check the error* \\n\\n[Open Pipeline]($CI_PIPELINE_URL)"

notify_error_job:
  extends: .notify
  script:
    - |
      printf '{"chat_id": "%s", "text": "%s", "parse_mode": "Markdown"}' \
        "$TELEGRAM_CHAT_ID" "$MESSAGE_FAILURE" |
      curl -s -X POST \
        -H "Content-Type: application/json" \
        -d @- \
        "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage"
  when: on_failure

notify_success_job:
  extends: .notify
  script:
    - pwd
    - ./notify.sh $MESSAGE_SUCCESS
  when: on_success
