rollback_job:
  stage: rollback
  needs:
    - job: deploy_job
  script:
    - echo "Current application version - $APP_VERSION"
    - PREVIOUS_VERSION=$(echo "${CURRENT_VERSION:1}" | awk -F. '{print "v"$1"."($2-1)}')
    - echo "Rollback the application to a previous version ($PREVIOUS_VERSION) ..."
  when: manual
